### ISSUE TITLE
imagenes desbordadas

### ISSUE THREAD

**Issue by UrielMiranda** [ctcmiguel/ctcmiguel.github.io#1]
hola Miguel, revisando las imagenes en mobile o responsive, se desbordan de sus contenedores, boostrap tiene una clase para hacerlas responsivas ["img-fluid" ](https://getbootstrap.com/docs/4.0/content/images/)

y para finalizar, la imagen principal, estaria bien un margin-bottom para que le de ese espacio, eso es opcional, pero creo que le daria un toque estetico

**Comment by ctcmiguel** [comment]
Listo ya los arregle, gracias
